# Generated by Django 3.0.4 on 2020-04-21 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hp', '0005_auto_20200421_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='dr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
