# Generated by Django 3.0.4 on 2020-04-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0007_auto_20200421_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_status',
            field=models.CharField(choices=[('Attended', 'Attended'), ('Not Attended', 'Not Attended')], default='Not Attended', max_length=15),
        ),
    ]
