# Generated by Django 3.0.4 on 2020-04-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0008_complaint_complaint_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='datetime',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Not confirmed', 'Not confirmed')], default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='visitor',
            name='checkin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='visitor',
            name='checkout',
            field=models.DateTimeField(default=None),
        ),
    ]
