# Generated by Django 3.0.4 on 2020-04-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0014_auto_20200422_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.CharField(choices=[('Receiptionist', 'Receiptionist'), ('Patient', 'Patient'), ('Nurse', 'Nurse'), ('Doctor', 'Doctor'), ('Staff', 'Staff')], max_length=17),
        ),
    ]
