# Generated by Django 3.0.4 on 2020-04-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0015_auto_20200422_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='work',
            field=models.CharField(max_length=50),
        ),
    ]
