# Generated by Django 3.0.4 on 2020-04-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0016_auto_20200422_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='routine',
            field=models.CharField(max_length=80),
        ),
    ]
