# Generated by Django 3.0.4 on 2020-04-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0017_auto_20200422_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='reply',
            field=models.CharField(default='Will be answered shortly', max_length=50),
        ),
    ]
