# Generated by Django 3.0.4 on 2020-04-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0018_complaint_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='visitor_names',
            field=models.CharField(default='No name', max_length=200),
        ),
    ]
