# Generated by Django 3.0.4 on 2020-04-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0020_auto_20200422_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='visitor_details',
            field=models.CharField(default='No name', max_length=300),
        ),
    ]
