# Generated by Django 3.0.4 on 2020-04-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0021_auto_20200422_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='room',
            field=models.CharField(default='', max_length=7),
        ),
    ]
