# Generated by Django 3.0.4 on 2020-04-22 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0022_complaint_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_time',
            field=models.TimeField(default=datetime.time(11, 41, 50, 478342)),
        ),
    ]
