# Generated by Django 3.0.4 on 2020-04-22 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0023_complaint_complaint_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='remarks',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Not confirmed', 'Not confirmed'), ('Declined', 'Declined')], default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_time',
            field=models.TimeField(default=datetime.time(14, 32, 41, 332515)),
        ),
    ]
