# Generated by Django 3.0.4 on 2020-04-23 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0024_auto_20200422_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='complaint_time',
        ),
        migrations.AddField(
            model_name='complaint',
            name='complaint_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 23, 6, 33, 39, 279660)),
        ),
    ]
