# Generated by Django 3.0.4 on 2020-04-19 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('reason', models.TextField(max_length=50)),
                ('grant_status', models.CharField(choices=[('Y', 'Granted'), ('N', 'Not Granted')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('work_area', models.CharField(max_length=20)),
                ('profession', models.CharField(choices=[('Nurse', 'Nurse'), ('Doctor', 'Doctor'), ('Staff', 'Staff')], max_length=7)),
                ('present_count', models.IntegerField()),
                ('absent_count', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('work_time', models.TimeField()),
                ('work', models.CharField(max_length=15)),
                ('dr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_date', models.DateField()),
                ('mark_status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], max_length=1)),
                ('dr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Profile')),
            ],
        ),
    ]
