# Generated by Django 3.0.4 on 2020-04-20 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='dr',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='doctor.Profile'),
        ),
    ]
