# Generated by Django 3.0.4 on 2020-04-20 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_leave_dr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='dr',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='dr',
        ),
        migrations.DeleteModel(
            name='Attendence',
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
